;This program plots a histogram of the data generated by gaussian_noise.f90 to verify that it is indeed Gaussian noise
nx=10000000
nbin=100
;nbin=4
x=fltarr(nx)
openr,20,'x.out'
readf,20,x
close,20
;print,x
plot,x
binvals=findgen(nbin)/(nbin-1)-0.5
;hist=histogram(x,nbins=nbin)
hist=histogram(x,binsize=1./nbin,locations=binvals)
plot,binvals,hist
oplot,[0,0],[0,nx],li=1
oplot,binvals,max(hist)*exp(-binvals^2/2),col=100
end
